# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ward < Formula
  desc "WardScribe CLI - Write once. Deploy everywhere."
  homepage "https://wardscribe.io"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/BabalolaBrainiac/wardscribe-v2/releases/download/v0.1.0/ward_0.1.0_darwin_amd64.tar.gz"
      sha256 "290d37bdbfac1ee4a6efe05bb278d3c60ff5e6125e4640e2cf6445f390cf5844"

      define_method(:install) do
        bin.install "ward"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/BabalolaBrainiac/wardscribe-v2/releases/download/v0.1.0/ward_0.1.0_darwin_arm64v.tar.gz"
      sha256 "d2f8b112eb102ac411a32a13ee2875cd82e3278dc953dfa71537cd25ff869f08"

      define_method(:install) do
        bin.install "ward"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/BabalolaBrainiac/wardscribe-v2/releases/download/v0.1.0/ward_0.1.0_linux_amd64.tar.gz"
      sha256 "2e2e91a0fd5085ed74e65478da375aceb85c3a313e4b6a29110f4e237c8452a2"
      define_method(:install) do
        bin.install "ward"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/BabalolaBrainiac/wardscribe-v2/releases/download/v0.1.0/ward_0.1.0_linux_armv6v.tar.gz"
      sha256 "f71584c3958f6756acb2f82448ab91c88fd029a15403416c94e353b15ed5c5dc"
      define_method(:install) do
        bin.install "ward"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BabalolaBrainiac/wardscribe-v2/releases/download/v0.1.0/ward_0.1.0_linux_arm64v.tar.gz"
      sha256 "4c81aad691a8cafb84123ce23df73f4cf36ad71b355d602e4bdb22edaaa012b5"
      define_method(:install) do
        bin.install "ward"
      end
    end
  end

  test do
    system "#{bin}/ward", "-v"
  end
end
