# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ward < Formula
  desc "WardScribe CLI - Write once. Deploy everywhere."
  homepage "https://wardscribe.io"
  version "0.9.0-beta.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/BabalolaBrainiac/wardscribe-v2/releases/download/v0.9.0-beta.1/ward_0.9.0-beta.1_darwin_amd64.tar.gz"
      sha256 "562a34c8827fd72b6d381185b27286809aefdac5ceb76b48b2dedb0995e8791b"

      define_method(:install) do
        bin.install "ward"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/BabalolaBrainiac/wardscribe-v2/releases/download/v0.9.0-beta.1/ward_0.9.0-beta.1_darwin_arm64v.tar.gz"
      sha256 "34a6131de5db50bc5ce6632e855f767bfac22ca9724f5329291a0a1395372990"

      define_method(:install) do
        bin.install "ward"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/BabalolaBrainiac/wardscribe-v2/releases/download/v0.9.0-beta.1/ward_0.9.0-beta.1_linux_amd64.tar.gz"
      sha256 "a48ceee7199ad3e305245a0caa5a6f92b86baf531cffc5c94d459af9f9015937"
      define_method(:install) do
        bin.install "ward"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/BabalolaBrainiac/wardscribe-v2/releases/download/v0.9.0-beta.1/ward_0.9.0-beta.1_linux_armv6v.tar.gz"
      sha256 "9dccae3098225855958f2c43812e8dbbd9f85d27d7e0d663c731403a25f1e826"
      define_method(:install) do
        bin.install "ward"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BabalolaBrainiac/wardscribe-v2/releases/download/v0.9.0-beta.1/ward_0.9.0-beta.1_linux_arm64v.tar.gz"
      sha256 "ad65fb061ea553edbb958825d1dab8ee313f75e5aa28562f95cfed7e1b32ed46"
      define_method(:install) do
        bin.install "ward"
      end
    end
  end

  test do
    system "#{bin}/ward", "-v"
  end
end
