# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ward < Formula
  desc "WardScribe CLI - Write once. Deploy everywhere."
  homepage "https://wardscribe.io"
  version "0.9.0-beta.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/BabalolaBrainiac/wardscribe-v2/releases/download/v0.9.0-beta.1/ward_0.9.0-beta.1_darwin_amd64.tar.gz"
      sha256 "1f1521932185db53d8552d624bba41a85f990f4e51e6d41575a9f65d52ed7f81"

      define_method(:install) do
        bin.install "ward"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/BabalolaBrainiac/wardscribe-v2/releases/download/v0.9.0-beta.1/ward_0.9.0-beta.1_darwin_arm64v.tar.gz"
      sha256 "5649809d3342e8a8a0ebaf675a3c9a9eeea5337e18fbc2c9a91c08bd187feb3a"

      define_method(:install) do
        bin.install "ward"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/BabalolaBrainiac/wardscribe-v2/releases/download/v0.9.0-beta.1/ward_0.9.0-beta.1_linux_amd64.tar.gz"
      sha256 "041f4620ec43b17e1c608030cfdfba0748d34bda1db20594e818988c60d6e0e2"
      define_method(:install) do
        bin.install "ward"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/BabalolaBrainiac/wardscribe-v2/releases/download/v0.9.0-beta.1/ward_0.9.0-beta.1_linux_armv6v.tar.gz"
      sha256 "1cd8bcbe4b0c4052ad2df94f701e5f2a17cf8e949ff1ad48b036d8321f1fbcd5"
      define_method(:install) do
        bin.install "ward"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BabalolaBrainiac/wardscribe-v2/releases/download/v0.9.0-beta.1/ward_0.9.0-beta.1_linux_arm64v.tar.gz"
      sha256 "100662d5736cd52577284d0639dff8d29011192c144edde9697fe98e2758077b"
      define_method(:install) do
        bin.install "ward"
      end
    end
  end

  test do
    system "#{bin}/ward", "-v"
  end
end
